language: java
jdk:
- oraclejdk8

# Handle git submodules yourself
git:
    submodules: false

install:
- git clone https://github.com/RoboticsTeam4904/wpilib-mirror.git ~/wpilib
- curl -o ~/wpilib/java/current/lib/navx.jar http://www.t4904.xyz/wiki/files/navx/navx.jar
- curl -o ~/wpilib/java/current/lib/navx_frc.jar http://www.t4904.xyz/wiki/files/navx/navx_frc.jar
- curl -o ~/wpilib/java/current/ant/build.properties http://www.t4904.xyz/wiki/files/navx/build.properties

notifications:
  email: none

script: ant compile
